trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: UnitTest
  jobs:
  - job: UnitTests
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Run Unit Tests"
        inputs:
          command: 'test'
          projects: '**/HSEPortal.API.UnitTests.csproj'

- stage: DEV
  dependsOn: UnitTest
  variables: 
  - group: HSEPortal-DEV
  jobs:
  - job: DevDeploy
    steps:
    - task: AzureCLI@2
      displayName: Deploy Bicep template
      inputs:
        azureSubscription: 's118-dev-bsr-acs-services'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: | 
                    az group create --name $(resourceGroupName) --location uksouth
                    az deployment group create --resource-group $(resourceGroupName) --template-file '$(Build.SourcesDirectory)/infraestructure/main.bicep' --parameters environment='$(env)'

    - task: AzureFunctionApp@1
      displayName: Deploy Function App
      inputs:
        azureSubscription: 's118-dev-bsr-acs-services'
        appType: 'functionAppLinux'
        appName: 's118-$(env)-itf-acs-portal-fa'
        package: 'HSEPortal.API'

    - task: AzureCLI@2
      displayName: Get SWA Secret
      inputs:
        azureSubscription: 's118-dev-bsr-acs-services'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: | 
                    $swa = az staticwebapp secrets list --name 's118-$(env)-itf-acs-portal-swa' | ConvertFrom-Json
                    Write-Host "##vso[task.setvariable variable=swaToken;issecret=true]$($swa.properties.apiKey)"

    - task: AzureStaticWebApp@0
      displayName: Deploy SWA to DEV
      inputs:
        app_location: 'HSEPortal.Client'
        app_build_command: 'npm run prerender'
        output_location: 'dist/hseportalclient/browser'
        azure_static_web_apps_api_token: $(swaToken)