trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: UnitTest
  jobs:
  - job:
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Run Unit Tests"
        inputs:
          command: 'test'
          projects: '**/HSEPortal.API.UnitTests.csproj'

- stage: Infraestructure
  dependsOn: UnitTest
  variables: 
  - group: HSEPortal-DEV
  jobs:
  - job: 
    steps:
    - task: AzureCLI@2
      displayName: Deploy Bicep template
      inputs:
        azureSubscription: 's118-dev-bsr-acs-services'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: | 
                    az group create --name $(resourceGroupName) --location uksouth
                    az deployment group create --resource-group $(resourceGroupName) --template-file '$(Build.SourcesDirectory)/infraestructure/main.bicep' `
                      --parameters swaName='$(swaName)' swaLocation='westeurope'

- stage: DEV
  dependsOn: Infraestructure
  variables: 
  - group: HSEPortal-DEV
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      displayName: Get SWA Secret
      inputs:
        azureSubscription: 's118-dev-bsr-acs-services'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: | 
                    az staticwebapp secrets list --name $(swaName)
                    | Tee-Object -Variable swa
                    $swaObject = $swa | ConvertFrom-Json
                    ##vso[task.setvariable variable=swaToken]$($swaObject.properties.apiKey)
    - task: AzureStaticWebApp@0
      displayName: Deploy SWA to DEV
      inputs:
        app_location: 'HSEPortal.Client'
        app_build_command: 'npm run prerender'
        output_location: 'dist/hseportalclient/browser'
        api_location: 'HSEPortal.API'
        azure_static_web_apps_api_token: $(swaToken)