trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: HSEPORTAL

stages:
- stage: Infraestructure
  variables: 
  - group: HSEPortal-DEV
  jobs:
  - job: 
    steps:
    - task: AzureCLI@2
      displayName: Deploy Bicep template
      inputs:
        azureSubscription: 's118-dev-bsr-acs-services'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: | 
                    az group create --name $(resourceGroupName) --location uksouth
                    az deployment group create --resource-group $(resourceGroupName) --template-file '$(Build.SourcesDirectory)/infraestructure/main.bicep' `
                      --parameters swaName='$(swaName)' swaLocation='westeurope' `
                      | Tee-Object -Variable deployment
                      $AzDeployment = $deployment | ConvertFrom-Json
                      ##vso[task.setvariable variable=swaToken]$($AzDeployment.properties.outputs.swaToken)

# - stage: DEV
#   variables: 
#   - group: HSEPortal-DEV
#   jobs:
#   - job:
#     steps:
#     - task: AzureStaticWebApp@0
#       displayName: Deploy SWA to DEV
#       inputs:
#         app_location: 'HSEPortal.Client'
#         app_build_command: 'npm run prerender'
#         output_location: 'dist/hseportalclient/browser'
#         api_location: 'HSEPortal.API'
#         azure_static_web_apps_api_token: $(swaToken)